# Generated by Django 4.0.5 on 2022-06-25 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('class_strength', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_class', models.PositiveIntegerField()),
                ('course_videos', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=100)),
                ('volunteer_resume', models.FileField(upload_to='')),
                ('volunteer_duration', models.PositiveIntegerField()),
                ('volunteer_Specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_age', models.PositiveIntegerField()),
                ('student_city', models.CharField(max_length=100)),
                ('student_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.class')),
            ],
        ),
        migrations.CreateModel(
            name='question_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('user_answered', models.ManyToManyField(related_name='answer', to='home.students')),
                ('user_asked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask', to='home.students')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedack_message', models.TextField()),
                ('associated_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.volunteer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.students')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='class_volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.volunteer'),
        ),
        migrations.AddField(
            model_name='class',
            name='courses_assigned',
            field=models.ManyToManyField(to='home.courses'),
        ),
    ]
