# Generated by Django 4.0.5 on 2022-06-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_courses_course_credits_tests_test_subject_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_videos',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_resume',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_videos_link',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
